---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages
    apt: 
      update_cache: yes
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: install apache2 and php packages
    dnf: 
      update_cache: yes
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"