---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt: 
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: remove apache2 package
    apt: 
      name: apache2
      state: absent
    when: ansible_distribution == "Debian"

  - name: add PHP support for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Debian"